### ISSUE TITLE
Server failing to connect to PeerJS client

### ISSUE THREAD

**Issue by pinto-pinto** [pinto-pinto/pinto#15]
### What is the problem?
_When the server approaches its **sixth** PeerJS client  litlmoz/pinto-pinto#28 connections, each subsequent connection takes longer to establish._

_Once the **eighth** PeerJS connection is reached, socket.io starts to receive client requests that lack a room name._
_Socket.io logs disconnect and reports `ping timeout` from the client connection._ 

_**Expected** - Load **seven** or **eight** tabs without PeerJS client disconnects._

### Steps to Reproduce
- [ ] Connect basic HTML WebRTC client to public ExpressPeerServer
> Isolate custom ExpressPeerServer configuration, from causing disconnects.

### Versions:
Server
```
socket.io:  3.1.1
peer:       0.6.1
stack:      OVHcloud
Node.js:    10.17.17
```
Client
```
socket.io-client: 3.1.1
peerjs:           1.3.1
express:          4.17.1
LTS Node.js:      14.15.5
```

**Comment by Litlmoz** [comment]
### Steps to Reproduce
- [ ] Connect basic HTML WebRTC client to ExpressPeerServer, replace client Google STUN server with 
Twilio
> TURN server is not needed to establish reliable PeerJS client connection

### Versions:
Server
```
socket.io:  3.1.1
peer:       0.6.1
stack:      Heroku-20
Node.js:    15.8.0
```
Client
```
socket.io-client: 3.1.1
peerjs:           1.3.1
express:          4.17.1
LTS Node.js:      14.15.5
```
